# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - name: Install Python3.8.5
      run: |
        curl https://www.python.org/ftp/python/3.8.5/python-3.8.5-macosx10.9.pkg -o python.pkg
        sudo installer -pkg python.pkg -target /
    - name: Install py2app
        pip3 install py2app
    - name: Setup
      run: |
        /Library/Frameworks/Python.framework/Versions/3.8/bin/py2applet --make-setup Scripts/shortcut.icns ProperTree.py
        python3 setup.py py2app
