# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python3 -V
        which python3
        which pip3
        curl https://www.python.org/ftp/python/3.8.5/python-3.8.5-macosx10.9.pkg -o python.pkg
        sudo installer -pkg python.pkg -target /
        python3 -V
        pip3 install py2app
        which python3
        which pip3
        ls /usr/local/bin
    - name: Build
      run: |
        py2applet --make-setup Scripts/shortcut.icns ProperTree.py
        python3 setup.py py2app
